apiVersion: v1
kind: Pod
metadata:
  name: ansuya-container-transfer
  namespace: parabricks
  labels:
    app: container-transfer
    user: ansuya
spec:
  restartPolicy: Never
  serviceAccountName: parabricks-builder  # Needs permission to push to internal registry
  volumes:
  - name: parabricks-data
    persistentVolumeClaim:
      claimName: parabricks-data
  - name: container-storage
    emptyDir:
      sizeLimit: 50Gi  # Temporary storage for container images
  containers:
  - name: podman-skopeo
    image: quay.io/podman/stable:latest
    command: ["/bin/sh", "-c", "sleep infinity"]
    stdin: true
    tty: true
    securityContext:
      # Podman needs these for rootless operation
      runAsUser: 1000
      allowPrivilegeEscalation: true
      capabilities:
        add:
        - SETUID
        - SETGID
    volumeMounts:
    - name: parabricks-data
      mountPath: /data
    - name: container-storage
      mountPath: /var/lib/containers
    env:
    - name: STORAGE_DRIVER
      value: "vfs"  # Works in OpenShift without overlay
    - name: BUILDAH_ISOLATION
      value: "chroot"
    resources:
      requests:
        memory: "4Gi"
        cpu: "1"
      limits:
        memory: "8Gi"
        cpu: "2"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: parabricks-builder
  namespace: parabricks
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: parabricks-builder-image-builder
  namespace: parabricks
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-builder
subjects:
- kind: ServiceAccount
  name: parabricks-builder
  namespace: parabricks
