# Parabricks Jupyter Workbench with Bakta and all genomics tools
# This is the WORKING configuration tested with Ansuya's E. coli data

FROM nvcr.io/nvidia/clara/clara-parabricks:4.6.0-1 AS parabricks-source

FROM image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/jupyter-datascience-cpu-py312-ubi9:2025.1

LABEL maintainer="platform-team" \
      name="parabricks-workbench" \
      version="1.6.0" \
      description="Parabricks workbench with Bakta, Conda, and all genomics tools"

USER 0

# Install build dependencies
RUN dnf install -y --setopt=tsflags=nodocs \
    wget bzip2 gcc gcc-c++ make zlib-devel bzip2-devel xz-devel ncurses-devel \
    && dnf clean all

# Install samtools
RUN cd /tmp && \
    wget https://github.com/samtools/samtools/releases/download/1.19.2/samtools-1.19.2.tar.bz2 && \
    tar -xjf samtools-1.19.2.tar.bz2 && \
    cd samtools-1.19.2 && \
    ./configure --prefix=/usr/local && make && make install && \
    cd /tmp && rm -rf samtools-1.19.2*

# Install htslib (includes tabix)
RUN cd /tmp && \
    wget https://github.com/samtools/htslib/releases/download/1.19.1/htslib-1.19.1.tar.bz2 && \
    tar -xjf htslib-1.19.1.tar.bz2 && \
    cd htslib-1.19.1 && \
    ./configure --prefix=/usr/local && make && make install && \
    cd /tmp && rm -rf htslib-1.19.1*

# Install bcftools
RUN cd /tmp && \
    wget https://github.com/samtools/bcftools/releases/download/1.19/bcftools-1.19.tar.bz2 && \
    tar -xjf bcftools-1.19.tar.bz2 && \
    cd bcftools-1.19 && \
    ./configure --prefix=/usr/local && make && make install && \
    cd /tmp && rm -rf bcftools-1.19*

# Install bwa
RUN cd /tmp && \
    wget https://github.com/lh3/bwa/releases/download/v0.7.17/bwa-0.7.17.tar.bz2 && \
    tar -xjf bwa-0.7.17.tar.bz2 && \
    cd bwa-0.7.17 && \
    sed -i 's/const uint8_t rle_auxtab\[8\];/extern const uint8_t rle_auxtab[8];/' rle.h && \
    make && cp bwa /usr/local/bin/ && \
    cd /tmp && rm -rf bwa-0.7.17*

# Install SRA Toolkit
RUN cd /tmp && \
    wget https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/3.2.0/sratoolkit.3.2.0-centos_linux64.tar.gz && \
    tar -xzf sratoolkit.3.2.0-centos_linux64.tar.gz && \
    cp -r sratoolkit.3.2.0-centos_linux64/bin/* /usr/local/bin/ && \
    rm -rf sratoolkit.3.2.0-centos_linux64*

# Install EDirect
RUN cd /tmp && \
    dnf install -y perl perl-App-cpanminus perl-LWP-Protocol-https && \
    wget https://ftp.ncbi.nlm.nih.gov/entrez/entrezdirect/edirect.tar.gz && \
    tar -xzf edirect.tar.gz && \
    mkdir -p /usr/local/edirect && \
    cp -r edirect/* /usr/local/edirect/ && \
    rm -rf edirect* && \
    dnf clean all

# Install GATK
RUN cd /tmp && \
    wget https://github.com/broadinstitute/gatk/releases/download/4.6.1.0/gatk-4.6.1.0.zip && \
    dnf install -y unzip java-17-openjdk && \
    unzip gatk-4.6.1.0.zip && \
    mv gatk-4.6.1.0 /usr/local/gatk && \
    ln -s /usr/local/gatk/gatk /usr/local/bin/gatk && \
    rm -rf gatk-4.6.1.0.zip && \
    dnf clean all

# Install Miniforge (conda without TOS issues)
RUN cd /tmp && \
    wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh && \
    bash Miniforge3-Linux-x86_64.sh -b -p /opt/conda && \
    rm Miniforge3-Linux-x86_64.sh

# Install Bakta and gperftools via mamba
RUN /opt/conda/bin/mamba install -y -c conda-forge -c bioconda bakta gperftools && \
    /opt/conda/bin/mamba clean -afy

# Copy Parabricks from source image
COPY --from=parabricks-source /usr/local/parabricks /opt/parabricks
COPY --from=parabricks-source /usr/lib/x86_64-linux-gnu/libboost_*.so.1.74.0 /usr/lib64/

# Setup boost library symlinks
RUN cd /usr/lib64 && \
    for lib in libboost_*.so.1.74.0; do \
        ln -sf "$lib" "${lib%.1.74.0}"; \
    done && \
    ldconfig

# Set environment variables - CRITICAL: correct library paths
ENV PATH="/opt/conda/bin:/opt/parabricks:/usr/local/edirect:${PATH}" \
    LD_LIBRARY_PATH="/opt/conda/lib:/opt/parabricks/binaries/lib:/usr/lib64:${LD_LIBRARY_PATH}"

# Install Python packages
RUN pip install --no-cache-dir biopython==1.86 pysam==0.23.3 pandas numpy matplotlib seaborn

# Setup directories and permissions
RUN mkdir -p /opt/app-root/src/notebooks && \
    chown -R 1001:0 /opt/app-root/src /opt/parabricks /opt/conda && \
    chmod -R g+w /opt/app-root/src /opt/conda && \
    chmod -R g+rx /opt/parabricks

USER 1001
WORKDIR /opt/app-root/src
CMD ["/opt/app-root/bin/start-notebook.sh"]
