apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: parabricks-workbench-build
  namespace: parabricks
  labels:
    app: parabricks-workbench
    component: jupyter-notebook
spec:
  output:
    to:
      kind: ImageStreamTag
      name: parabricks-workbench:1.1.0  # New version with Podman
  resources:
    limits:
      cpu: "2"
      memory: 4Gi
    requests:
      cpu: "1"
      memory: 2Gi
  source:
    dockerfile: |
      FROM image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/jupyter-datascience-cpu-py312-ubi9:2025.1

      LABEL maintainer="platform-team" \
            name="parabricks-workbench" \
            version="1.1.0" \
            description="Jupyter environment with Podman and Clara Parabricks for genomics analysis" \
            io.k8s.description="Jupyter workbench with Podman, Clara Parabricks, BioPython, PySam, and genomics tools" \
            io.k8s.display-name="Clara Parabricks Workbench with Podman" \
            io.openshift.tags="jupyter,python,genomics,parabricks,bioinformatics,podman"

      USER 0

      # Install Podman and system dependencies
      RUN dnf install -y --setopt=tsflags=nodocs \
          podman \
          wget \
          bzip2 \
          fuse-overlayfs \
          slirp4netns \
          && dnf clean all \
          && rm -rf /var/cache/dnf

      # Configure Podman for rootless operation
      RUN mkdir -p /etc/containers && \
          echo '[storage]' > /etc/containers/storage.conf && \
          echo 'driver = "vfs"' >> /etc/containers/storage.conf && \
          echo '[storage.options]' >> /etc/containers/storage.conf && \
          echo 'mount_program = "/usr/bin/fuse-overlayfs"' >> /etc/containers/storage.conf

      # Create placeholder pbrun script
      RUN mkdir -p /opt/parabricks && \
          echo '#!/bin/bash' > /opt/parabricks/pbrun && \
          echo 'echo "Clara Parabricks pbrun - Version 4.6.0-1"' >> /opt/parabricks/pbrun && \
          echo 'echo "Ready for genomics analysis"' >> /opt/parabricks/pbrun && \
          echo 'echo ""' >> /opt/parabricks/pbrun && \
          echo 'if [ "$1" == "--help" ] || [ "$1" == "-h" ] || [ "$1" == "version" ]; then' >> /opt/parabricks/pbrun && \
          echo '    echo "Available commands: germline, fq2bam, haplotypecaller, mutectcaller"' >> /opt/parabricks/pbrun && \
          echo '    echo "This is a demonstration wrapper."' >> /opt/parabricks/pbrun && \
          echo '    echo "In production, integrate with real Parabricks installation."' >> /opt/parabricks/pbrun && \
          echo 'fi' >> /opt/parabricks/pbrun

      RUN chmod +x /opt/parabricks/pbrun

      ENV PATH="/opt/parabricks:${PATH}"

      # Install Python packages
      RUN pip install --no-cache-dir --upgrade pip && \
          pip install --no-cache-dir \
          biopython==1.86 \
          pysam==0.23.3 \
          pandas==2.3.2 \
          matplotlib==3.10.6 \
          seaborn==0.13.2

      # Set permissions for OpenShift
      RUN mkdir -p /opt/app-root/src/notebooks && \
          chown -R 1001:0 /opt/app-root/src /opt/parabricks /etc/containers && \
          chmod -R g+w /opt/app-root/src /etc/containers && \
          chmod -R g+rx /opt/parabricks

      USER 1001
      WORKDIR /opt/app-root/src
      CMD ["/opt/app-root/bin/start-notebook.sh"]
    type: Dockerfile
  strategy:
    dockerStrategy:
      noCache: false
    type: Docker
  triggers:
  - type: ConfigChange
